apiVersion: v1
kind: Service

metadata:
  name: deployment-app-service

spec:
  type: NodePort

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081

  selector:
    app: deployment-app
